# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

default_platform(:ios)

import "./Variables.env"
import("./extensions/Building.rb")
import("./extensions/Certificates.rb")
import("./extensions/Discord.rb")
import("./extensions/Icon.rb")
import("./extensions/ItunesConnect.rb")
import("./extensions/Testflight.rb")

platform :ios do

  desc "Install all project dependencies (cocoapods)"
  lane :install do
    cocoapods(repo_update: true, clean_install: true, use_bundle_exec: true)
  end
end